openapi: 3.0.0
info:
  title: Client API
  description: API documentation for the client operations
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /clients:
    get:
      summary: Get all clients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
    post:
      summary: Register a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
  /clients/{id}:
    get:
      summary: Get a client by ID
      parameters:
        - name: id
          in: path
          description: Client ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    put:
      summary: Update a client
      parameters:
        - name: id
          in: path
          description: Client ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    delete:
      summary: Delete a client
      parameters:
        - name: id
          in: path
          description: Client ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
