import { Client } from './Client';

export const CLIENT_PROPERTIES: { [K in keyof Client]: K } = {
  id: 'id',
  userName: 'userName',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  password: 'password',
  // profilePictureUrl: 'profilePictureUrl',
  status: 'status',
  dateOfBirth: 'dateOfBirth',
  phoneNumber: 'phoneNumber',
  isAdmin: 'isAdmin',
  goal: 'goal',
  activityLevel: 'activityLevel',
  height: 'height',
  weight: 'weight',
  gender: 'gender',
  dietaryRestrictions: 'dietaryRestrictions',
  calorieTarget: 'calorieTarget',
  macronutrientRatios: 'macronutrientRatios',
  mealSchedule: 'mealSchedule',
  waterIntake: 'waterIntake',
  allergies: 'allergies',
  favoriteRecipes: 'favoriteRecipes',
  generateAccessToken: 'generateAccessToken',
  validatePassword: 'validatePassword',
  hasId: 'hasId',
  save: 'save',
  remove: 'remove',
  softRemove: 'softRemove',
  recover: 'recover',
  reload: 'reload',
};
